apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sb-app1
spec:
  replicas: 1
  template:
    metadata:
      name: sb-app1
      labels:
        app: sb-app1
    spec:
      containers:
      - name: sb-app1
        image: 144026253291.dkr.ecr.us-east-1.amazonaws.com/springbootdocker:latest
        ports:
        - containerPort: 8080
        