apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sb-app
spec:
  selector:
    matchLabels:
      app: sb-app
  replicas: 2
  template:
    metadata:
      labels:
        app: sb-app
    spec:
      containers:
      - name: sb-app
        image: 144026253291.dkr.ecr.us-east-1.amazonaws.com/springbootdocker:latest
        ports:
        - containerPort: 8080
        