apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sb-app2
spec:
  selector:
    matchLabels:
      app: sb-app2
  replicas: 1
  template:
    metadata:
      labels:
        app: sb-app2
    spec:
      containers:
      - name: sb-app2
        image: 144026253291.dkr.ecr.us-east-1.amazonaws.com/springbootdocker2:latest
        ports:
        - containerPort: 8082
        