apiVersion: v1
kind: Service
metadata:
  name: sb-app2
  namespace: default
  labels:
    app: sb-app2
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: sb-app2
  type: LoadBalancer