apiVersion: v1
kind: Service
metadata:
  name: sb-app1
  namespace: default
  labels:
    app: sb-app1
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: sb-app1
  type: LoadBalancer