spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:derby:derbyDB;create=true
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
