spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:postgresql://database-1.cletlzmtdqdf.us-east-1.rds.amazonaws.com:5432/postgres"
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    #comment
  security:
    oauth2:
      client:
        registration:
          cognito-client-1:
            client-id: 3n8keouehcfl5tqll3kkco5en7
            client-secret: 54le05daac08ohs21vm3mqq9lcph8ftn16va6gf0429hb75tlr0
            client-name: Cognito Code Grant
            provider: cognito
            scope: openid
            # ローカル環境以外ではhttpsにする必要があり。
            redirectUri: https://www.mune183time.uk/login/oauth2/code/cognito
            authorization-grant-type: authorization_code
        provider:
          cognito:
            authorization-uri: https://361603813509.auth.us-east-1.amazoncognito.com/oauth2/authorize
            token-uri: https://361603813509.auth.us-east-1.amazoncognito.com/oauth2/token
            user-info-uri: https://361603813509.auth.us-east-1.amazoncognito.com/oauth2/userInfo
            jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_WqWPJF19s/.well-known/jwks.json
            user-name-attribute: cognito:username
server:
  port : 8080

#logging:
#  level:
#    root: DEBUG